name: build-clang
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout the source
      uses: actions/checkout@v3
      with:
        repository: "libjxl/libjxl"
        submodules: true

    - name: Install libraries with vcpkg
      shell: 'bash'
      run: |
        set -x
        vcpkg install gtest:x64-windows-static
        vcpkg install giflib:x64-windows-static
        vcpkg install libjpeg-turbo:x64-windows-static
        vcpkg install libpng:x64-windows-static
        vcpkg install zlib:x64-windows-static
        
    - name: Configure
      shell: 'bash'
      run: |
        set -x
        export CC=clang CXX=clang++
        mkdir build
        cmake -Bbuild -H. -A x64 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=`pwd`/prefix \
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DJPEGXL_STATIC=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_GMOCK=OFF \
          -Dgtest_force_shared_crt=ON \
          -DJPEGXL_ENABLE_TCMALLOC=OFF \          
          -DJPEGXL_ENABLE_FUZZERS=OFF \
          -DJPEGXL_ENABLE_VIEWERS=OFF -G Ninja
        ninja -C build  
        #
          
    
    - name: Get current timestamp      
      id: timestamp
      run: echo "::set-output name=date::$(date +%Y-%m-%d)"  
 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jxl-dev
        path: |
          prefix/*
 
    - name: Package release zip
      shell: 'powershell'
      run: |
        7z a jxl-dev.7z prefix/*
   
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: jxl*.7z
        tag: ${{ steps.timestamp.outputs.date }}
        overwrite: true
        file_glob: true
